import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css"; 
// import { useTranslation } from 'react-i18next';
import i18nServer from '../libs/i18n-server';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", 
});


export const metadata: Metadata = {
  title: "Frontend Demo",
  description: "Generated by Toricat",
  
};

import { cookies } from 'next/headers';

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const lang = (await cookies()).get('i18next')?.value || 'en';
  console.log("lang",lang);

  // i18n.changeLanguage(lang);
  await i18nServer.changeLanguage(lang); 
  const welcomeMessage = i18nServer.t('welcome_message'); 
  return (
    <html lang={lang} suppressHydrationWarning>
    <body className={inter.className|| ""}>
    <h1>{welcomeMessage}</h1>
        {children}
      </body>
    </html>
  );
}
