import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css"; 
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", 
});


export const metadata: Metadata = {
  title: "Frontend Demo",
  description: "Generated by Toricat",
  
};

import { cookies } from 'next/headers';

import { LanguageProvider} from "@/context/LanguageContext";
import { preloadTranslation } from "@/libs/preload";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const lang = (await cookies()).get('i18next')?.value || 'en';
  const { translations } = await preloadTranslation(lang, "translation"); 
  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={inter.className|| ""}>
    <LanguageProvider initialTranslations={translations} initialLang={lang}>
      {children}
    </LanguageProvider>
      </body>
    </html>
  );
}
