import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

import { getUserLanguage } from "@/libs/next-intl/language";
// import { NextIntlClientProvider } from 'next-intl';
// import {getMessages} from 'next-intl/server';
// import {notFound} from 'next/navigation';


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Frontend Demo",
  description: "Generated by Toricat",

};


import {NextIntlClientProvider} from 'next-intl';
import {getMessages , getLocale} from 'next-intl/server';
 
export  default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();
 
  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}